### ISSUE TITLE
Refactor Model

### ISSUE THREAD

**Issue by frankwiles** [simplworld/simpl-blackjack-model#3]
We need to refactor a bit of the model: 

- [ ] Create a `BlackJackRun` which sets the new user state up
- [ ] Create a method on `BlackJackRun` to create a new `BlackJackScenario`
- [ ] Create a method on `BlackJackScenario` to deal a new game

**Comment by janeeisenstein** [comment]
@frankwiles Are you suggesting each user has a separate run? Or just that the user registration/setup is handled by the single game run?

**Comment by frankwiles** [comment]
I liked your rewind idea better, so skipping my idea.
