### ISSUE TITLE
Model error results in database corruption

### ISSUE THREAD

**Issue by janeeisenstein** [simplworld/simpl-blackjack-model#5]
As discovered during the bootcamp, database corruption results if the dealer gets 21. This corruption prevents the player from logging in again.

**Comment by dinaluciano** [comment]
@frankwiles --any updates on this?

**Comment by frankwiles** [comment]
Still working on it! Ya'll will be the first to know when I have it licked!

**Comment by frankwiles** [comment]
This should be fixed now.
